//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gml.Launcher.Assets.Resources {
    using System;


    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gml.Launcher.Assets.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign in.
        /// </summary>
        public static string AuthButtonText {
            get {
                return ResourceManager.GetString("AuthButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Mods list.
        /// </summary>
        public static string ModsList {
            get {
                return ResourceManager.GetString("ModsList", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Website.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Website.
        /// </summary>
        public static string Cabinet {
            get {
                return ResourceManager.GetString("Cabinet", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProfileNotConfigured.
        /// </summary>
        public static string ProfileNotConfigured {
            get {
                return ResourceManager.GetString("ProfileNotConfigured", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProfileNotConfigured.
        /// </summary>
        public static string SettingsRamDescription {
            get {
                return ResourceManager.GetString("SettingsRamDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProfileNotConfigured.
        /// </summary>
        public static string SettingsRamTitle {
            get {
                return ResourceManager.GetString("SettingsRamTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProfileNotConfigured.
        /// </summary>
        public static string DynamicValue {
            get {
                return ResourceManager.GetString("DynamicValue", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProfileNotConfigured.
        /// </summary>
        public static string WindowSize {
            get {
                return ResourceManager.GetString("WindowSize", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProfileNotConfigured.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProfileNotConfigured.
        /// </summary>
        public static string UnitMb {
            get {
                return ResourceManager.GetString("UnitMb", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProfileNotConfigured.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
    }
}
